name: 'AppOverrideAction'
description: 'Create an override values for helm deployment'
inputs:
  app-name:
    description: 'Applcation id'
    default: ''
  debug:
    description: 'Debug mode'
    default: false
  helm-repo:
    description: 'helm repository'
    default: ''
  helm-ref:
    description: 'Ref to use for pulling helm repo'
    default: ''
  github-ssh:
    description: 'Github ssh key to pull helm chart repo from github'
    default: ''
  github-token:
    description: 'Github token to pull package to avoid limit rate'
    default: ''
  environment:
    description: 'Finalcad envrionment: production, staging, sandbox'
    default: ''
  regions:
    description: 'Finalcad List region'
    default: ''
  override-file:
    description: 'File with path for override files configuration'
    default: ''
  kubernetes-version:
    description: 'Kubernetes version to test against'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: "[deprecated] AppOverrideAction"
      shell: bash
      run: |
          cat <<EOF
          The Github Action https://github.com/FinalCAD/AppOverrideAction is deprecated. Use Gob (https://finalcad.atlassian.net/wiki/spaces/TE/pages/4264427522/Repository+update+by+Gob) to update your project.

          If you don't know what it means, post a message on Slack #infra-backend (https://finalcad.slack.com/archives/G01GL3EBLAW).
          EOF
          exit 1
